version: '2'

services:
  web:
    build: .
    environment:
      - WORDPRESS_DEBUG=true
      - QOVERY_DATABASE_WORDPRESS_USERNAME=the_db_user
      - QOVERY_DATABASE_WORDPRESS_PASSWORD=the_db_pass
      - QOVERY_DATABASE_WORDPRESS_NAME=the_db_name
      - QOVERY_DATABASE_WORDPRESS_HOST=mysql
      - QOVERY_ROUTER_MAIN_WORDPRESSFORA2SIDEDMARKET_URL=http://localhost:8080
    volumes:
      - .:/var/www/html/wp-content/plugins/split-market
    ports:
      - "8080:80"

  mysql:
    image: mariadb
    environment:
      - MYSQL_USER=the_db_user
      - MYSQL_PASSWORD=the_db_pass
      - MYSQL_DATABASE=the_db_name
      - MYSQL_ROOT_PASSWORD=the_root_pass
      - TERM=xterm
